### ISSUE TITLE
enhancement request: move credentials

### ISSUE THREAD

**Issue by fovea1959** [TheRoam/UNIHIKER-PAL#2]
Can credentials be moved to their own file so that the main code be kept in version control without having credentials in there?

See [this](https://janakiev.com/blog/python-credentials-and-configuration/#python-configuration-files).

**Comment by TheRoam** [comment]
yes sure. this was just a working sample but it's not optimized at all

when you say credentials you mean the WIFI credentials?

I like yaml configuration files. They are very similar to your reference library and it's a very common format. You can add all the available parameter settings. I'll work on a sample I can test.

**Comment by TheRoam** [comment]
I made a sample .yaml file and uploaded the script to read from it. Check the root folder for updated files.

Also updated the readme for instructions and a picture of the Unihiker filesystem for guidance.

You'll need to install pyyaml dependency to read the yaml file. Hope it's illustrative.

Thanks for your input ;)

**Comment by fovea1959** [comment]
Can the yaml file be renamed to PAL_config.yaml.template (with instructions to copy it to PAL_config.yaml) so that changes I make to the yaml file do not end up back in my git repository?

**Comment by TheRoam** [comment]
sure, if that helps.
